import TemplateSample from "../../../assets/images/template/TemplateSample.png"

const templateMockData = [
    {
      id: 1,
      title: "콘텐츠 마케터들을 위한 포트폴리오 템플릿",
      author: "유공돈",
      image: TemplateSample,
      liked: false,
      likesCount: 1,
      category: "콘텐츠 마케터",
    },
    {
      id: 2,
      title: "브랜드 마케터를 위한 포트폴리오 템플릿",
      author: "김민수",
      image: TemplateSample,
      liked: false,
      likesCount: 2,
      category: "브랜드 마케터",
    },
    {
      id: 3,
      title: "퍼포먼스 마케터를 위한 포트폴리오 템플릿",
      author: "이지현",
      image: TemplateSample,
      liked: false,
      likesCount: 3,
      category: "퍼포먼스 마케터",
    },
    {
      id: 4,
      title: "퍼포먼스 마케터들을 위한 포트폴리오 템플릿",
      author: "유공돈",
      image: TemplateSample,
      liked: false,
      likesCount: 4,
      category: "브랜드 마케터",
    },
    {
      id: 5,
      title: "브랜드 마케터를 위한 포트폴리오 템플릿",
      author: "김민수",
      image: TemplateSample,
      liked: false,
      likesCount: 5,
      category: "브랜드 마케터",
    },
    {
      id: 6,
      title: "퍼포먼스 마케터를 위한 포트폴리오 템플릿",
      author: "이지현",
      image: TemplateSample,
      liked: false,
      likesCount: 6,
      category: "퍼포먼스 마케터",
    },
    {
      id: 7,
      title: "퍼포먼스 마케터들을 위한 포트폴리오 템플릿",
      author: "유공돈",
      image: TemplateSample,
      liked: false,
      likesCount: 7,
      category: "브랜드 마케터",
    },
    {
      id: 8,
      title: "브랜드 마케터를 위한 포트폴리오 템플릿",
      author: "김민수",
      image: TemplateSample,
      liked: false,
      likesCount: 8,
      category: "브랜드 마케터",
    },
    {
      id: 9,
      title: "퍼포먼스 마케터를 위한 포트폴리오 템플릿",
      author: "이지현",
      image: TemplateSample,
      liked: false,
      likesCount: 9,
      category: "퍼포먼스 마케터",
    },
    {
      id: 10,
      title: "퍼포먼스 마케터들을 위한 포트폴리오 템플릿",
      author: "유공돈",
      image: TemplateSample,
      liked: false,
      likesCount: 10,
      category: "브랜드 마케터",
    },
    {
      id: 11,
      title: "브랜드 마케터를 위한 포트폴리오 템플릿",
      author: "김민수",
      image: TemplateSample,
      liked: false,
      likesCount: 150,
      category: "브랜드 마케터",
    },
    {
      id: 12,
      title: "퍼포먼스 마케터를 위한 포트폴리오 템플릿",
      author: "이지현",
      image: TemplateSample,
      liked: false,
      likesCount: 160,
      category: "퍼포먼스 마케터",
    },
  ];
  
export default templateMockData;